name: Render.com Keep Alive

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  ping_url:
    runs-on: ubuntu-latest
    name: Ping health check
    steps:
      - name: Check the URL
        id: ping
        uses: soul-wish/ping-url-javascript-action@v1.1
        with:
          url: 'https://toastr.onrender.com/api/health'
